# Generated by Django 3.1.6 on 2021-02-13 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('done', models.BooleanField(default=False)),
                ('notes', models.TextField(max_length=255, null=True)),
                ('priority', models.CharField(max_length=6, null=True)),
                ('dueto', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
